# Generated by Django 3.2.25 on 2025-07-28 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('parent_name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('class_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.classcategory')),
            ],
        ),
    ]
